### PR TITLE
chore: add zip package to docker image

### PR DESCRIPTION
**Pull request by Flo5k5**
- add zip and npm packages

### CODE REVIEW

**Comment by ayyouboulidi** [comment]
top 👍

**Comment by obalais** [comment]
> [@Flo5k5 ](/Flo5k5)

I don't see any npm package added here. Am I missing something?

**Comment by Flo5k5** [comment]
Still in test 🙇‍♂️

**Review by obalais — COMMENTED** [review]
Seems great!

**Pull request merged**
